//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TOProjects.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ProjectsEntities : DbContext
    {
        public ProjectsEntities()
            : base("name=ProjectsEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Contact> Contacts { get; set; }
        public DbSet<CustomerContact> CustomerContacts { get; set; }
        public DbSet<Employee> Employees { get; set; }
        public DbSet<EmployeeType> EmployeeTypes { get; set; }
        public DbSet<LeadSource> LeadSources { get; set; }
        public DbSet<LeadStatu> LeadStatus { get; set; }
        public DbSet<LeadType> LeadTypes { get; set; }
        public DbSet<Project> Projects { get; set; }
        public DbSet<ProjectNote> ProjectNotes { get; set; }
        public DbSet<Lead> Leads { get; set; }
        public DbSet<LeadNote> LeadNotes { get; set; }
        public DbSet<LeadCustomer> LeadCustomers { get; set; }
        public DbSet<Customer> Customers { get; set; }
        public DbSet<LeadContact> LeadContacts { get; set; }
    }
}
