//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TOProjects.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lead
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Lead()
        {
            this.LeadNotes = new HashSet<LeadNote>();
            this.LeadCustomers = new HashSet<LeadCustomer>();
        }
    
        public int Id { get; set; }
        public Nullable<int> LeadSourceId { get; set; }
        public Nullable<int> EmployeeId { get; set; }
        public Nullable<int> ProjectId { get; set; }
        public Nullable<int> LeadTypeId { get; set; }
        public Nullable<int> LeadStatusId { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string Address { get; set; }
        public Nullable<System.DateTime> BidDueDate { get; set; }
        public Nullable<System.DateTime> BidOpeningDate { get; set; }
        public Nullable<System.DateTime> FollowUpDate { get; set; }
        public string Quantity { get; set; }
        public string Name { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual LeadSource LeadSource { get; set; }
        public virtual LeadStatu LeadStatu { get; set; }
        public virtual LeadType LeadType { get; set; }
        public virtual Project Project { get; set; }
        public virtual Lead Lead1 { get; set; }
        public virtual Lead Lead2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LeadNote> LeadNotes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LeadCustomer> LeadCustomers { get; set; }
    }
}
