//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TOProjects.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LeadContactTable
    {
        public int ContactID { get; set; }
        public Nullable<int> CustomerID { get; set; }
        public Nullable<int> LeadID { get; set; }
        public Nullable<int> ccID { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual Lead Lead { get; set; }
    }
}
