//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TOProjects.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_lead_contact
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public Nullable<int> ContactID { get; set; }
        public Nullable<int> CustomerID { get; set; }
        public Nullable<int> LeadSourceId { get; set; }
        public Nullable<int> EmployeeId { get; set; }
        public Nullable<int> ProjectId { get; set; }
        public Nullable<int> LeadTypeId { get; set; }
        public Nullable<int> LeadStatusId { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string Address { get; set; }
        public Nullable<System.DateTime> BidDueDate { get; set; }
        public Nullable<System.DateTime> BidOpeningDate { get; set; }
        public Nullable<System.DateTime> FollowUpDate { get; set; }
        public string Quantity { get; set; }
        public Nullable<int> LeadID { get; set; }
        public int c_ID { get; set; }
        public int cm_ID { get; set; }
        public int cc_ID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string WorkPhone { get; set; }
        public string MobilePhone { get; set; }
        public string Email { get; set; }
        public string Title { get; set; }
        public string Notes { get; set; }
        public string CustomerInsuranceInformation { get; set; }
        public Nullable<bool> SendCreditApplication { get; set; }
    }
}
